// Code generated by "stringer -type ConnectorState -trimprefix State"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateInitial-0]
	_ = x[StateConfiguring-1]
	_ = x[StateConfigured-2]
	_ = x[StateStarting-3]
	_ = x[StateStarted-4]
	_ = x[StateRunning-5]
	_ = x[StateStopping-6]
	_ = x[StateStopped-7]
	_ = x[StateTorndown-8]
	_ = x[StateErrored-500]
}

const (
	_ConnectorState_name_0 = "InitialConfiguringConfiguredStartingStartedRunningStoppingStoppedTorndown"
	_ConnectorState_name_1 = "Errored"
)

var (
	_ConnectorState_index_0 = [...]uint8{0, 7, 18, 28, 36, 43, 50, 58, 65, 73}
)

func (i ConnectorState) String() string {
	switch {
	case 0 <= i && i <= 8:
		return _ConnectorState_name_0[_ConnectorState_index_0[i]:_ConnectorState_index_0[i+1]]
	case i == 500:
		return _ConnectorState_name_1
	default:
		return "ConnectorState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
